In [1]:
%load_ext autoreload
%autoreload 2
import os
os.environ["TERRA_CONFIG_PATH"] = "/home/sabri/code/spr-21/terra_config.json"

In [2]:
import pandas as pd
import torch

In [3]:
from robustnessgym.mosaic import NumpyArrayColumn, DataPane
import numpy as np
x = NumpyArrayColumn(np.random.rand(10))

In [16]:
np.random.rand(4)

array([0.3969655 , 0.26084479, 0.07127488, 0.51977011])

In [21]:
from itertools import product
list(product([True, False], [True, False]))

[(True, True), (True, False), (False, True), (False, False)]

In [24]:
np.array(["a", "b"]) + "a"

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> dtype('<U1')

In [14]:
x._data.std(axis=-1)

array([[0.13393184, 0.20494342, 0.17237425, 0.15306796, 0.2283244 ,
        0.2580918 , 0.39419763, 0.16173466, 0.2978883 , 0.10025193],
       [0.24573403, 0.26068341, 0.07345964, 0.25689204, 0.20571338,
        0.09627497, 0.1960636 , 0.21208213, 0.30562976, 0.25169601],
       [0.1034231 , 0.38428749, 0.37441479, 0.26001526, 0.29694927,
        0.21649289, 0.20056496, 0.0349294 , 0.34589923, 0.0892293 ],
       [0.23852083, 0.19868637, 0.16594739, 0.05685174, 0.27111653,
        0.33482958, 0.07793057, 0.15198732, 0.13845936, 0.40030449],
       [0.05032253, 0.29896422, 0.32935736, 0.16005516, 0.07588449,
        0.056382  , 0.16416194, 0.10563668, 0.27144883, 0.14217559],
       [0.29375854, 0.09950876, 0.36872824, 0.40139555, 0.30570615,
        0.06290767, 0.30967651, 0.28967073, 0.33149347, 0.31382214],
       [0.09729045, 0.23364453, 0.17794296, 0.06817671, 0.36508078,
        0.11142112, 0.23899214, 0.28765629, 0.30221951, 0.20908725],
       [0.44852626, 0.1170999 , 0.0828430

In [29]:
x

NumpyArrayColumn(array([1., 1...., 1., 1., 1.]))

In [25]:
x

NumpyArrayColumn(array([1., 1...., 1., 1., 1.]))

In [21]:
pd.Series([0,1,2,3])._repr_latex_()

In [3]:
import pickle
buf = pickle.dumps(x)
out = pickle.loads(buf)

obj is None
(1, (10,), dtype('float64'), False, b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?')


In [8]:
mixed_test_dp = DataPane.from_batch(
    {"a": np.arange(16), "b": list(np.arange(16)), "c": [{"a": 2}] * 16},
)


None
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
here [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [3]:
from robustnessgym.mosaic.contrib.wilds import WILDSInputColumn, WILDSDataPane
from robustnessgym.mosaic import DataPane
dp = WILDSDataPane(
    "fmow", 
    root_dir="/home/common/datasets/", 
    use_transform=True,
    split="val"
)

In [6]:
from spr.vision import Classifier
from spr.data.wilds import FMOW_CONFIG
model = Classifier(FMOW_CONFIG)

class ActivationExtractor:
    """Class for extracting activations of a targetted intermediate layer."""

    def __init__(self):
        self.activation = None

    def add_hook(self, module, input, output):
        self.activation = output

extractor = ActivationExtractor()
model.model.features[-1].register_forward_hook(extractor.add_hook);

loading weights from /home/common/datasets/fmow_v1.1/models/fmow_erm_ID_seed0/best_model.pth...
/home/common/envs/conda/envs/rg-sabri/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AUROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)


In [7]:
model.to(0).eval()


@torch.no_grad()
def predict(batch: dict):
    out = torch.softmax(model(torch.tensor(batch["input"]).to(0)), axis=-1)
    return {
        "pred": out.cpu().numpy().argmax(axis=-1),
        "probs": out.cpu().numpy(),
        "activation": extractor.activation.cpu().numpy()
    }

dp = dp.update(function=predict, batch_size=128, batched=True)

AssertionError: All columns must have equal length.

In [4]:
for x in dp[["y"]].batch(num_workers=4):
    print('a')

None
None
None
WorkerInfo(id=1, num_workers=2, seed=8857353981981808319, dataset=DataPane(num_rows: 11483))WorkerInfo(id=0, num_workers=2, seed=8857353981981808318, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=1, num_workers=2, seed=8857353981981808319, dataset=DataPane(num_rows: 11483))WorkerInfo(id=0, num_workers=2, seed=8857353981981808318, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=0, num_workers=2, seed=8857353981981808318, dataset=DataPane(num_rows: 11483))WorkerInfo(id=1, num_workers=2, seed=1430270452237157942, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=0, num_workers=2, seed=1430270452237157941, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=0, num_workers=2, seed=1430270452237157941, dataset=DataPane(num_rows: 11483))WorkerInfo(id=1, num_workers=2, seed=1430270452237157942, dataset=DataPane(num_rows: 11483))

DataPane(num_rows: 0)
DataPane(num_rows: 32)
None


AssertionError: All columns must have equal length.

In [4]:
for x in dp[["y"]].batch(num_workers=4):
    print('a')
    break

None
None
None
WorkerInfo(id=1, num_workers=2, seed=3881145194309886988, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=0, num_workers=2, seed=3881145194309886987, dataset=DataPane(num_rows: 11483))WorkerInfo(id=1, num_workers=2, seed=3881145194309886988, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=0, num_workers=2, seed=3881145194309886987, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=0, num_workers=2, seed=8589181887074536948, dataset=DataPane(num_rows: 11483))WorkerInfo(id=0, num_workers=2, seed=3881145194309886987, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=1, num_workers=2, seed=8589181887074536949, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=0, num_workers=2, seed=8589181887074536948, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=1, num_workers=2, seed=8589181887074536949, dataset=DataPane(num_rows: 11483))
DataPane(num_rows: 0)
DataPane(num_rows: 32)
a


In [18]:
x["y"]

(32,)


ValueError: Wrong number of items passed 32, placement implies 0

In [17]:
len(x.shape)

2

In [55]:
import pickle
pickle.dump(dp, file=open("test", 'wb'))

In [59]:
out = pickle.load(file=open("test", 'rb'))

EOFError: Ran out of input

In [13]:
for x in cell_dl:
    print(x)

In [61]:
dp.__getstate__()

AttributeError: 'WILDSDataPane' object has no attribute '__getstate__'

In [26]:
for x in cell_dl:
    print(x)

In [18]:
(dp["y"] == dp["pred"]).mean()

/home/common/envs/conda/envs/rg-sabri/lib/python3.8/site-packages/IPython/core/formatters.py:368: FormatterWarning: text/html formatter returned invalid type <class 'pandas.core.series.Series'> (expected <class 'str'>) for object: NumpyArrayColumn(array([0.6196116]))
  warnings.warn(


NumpyArrayColumn(array([0.6196116]))

In [19]:
dp["input"]._materialize = False

In [21]:
import pickle
pickle.dump(dp["y"], open("test", 'wb'))

In [24]:
out = pickle.load(open("test", "rb"))

EOFError: Ran out of input

In [30]:
import numpy as np
np.save("test.pkl", dp["y"])

In [32]:
out = np.load("test.pkl.npy")

In [33]:
out

array([ 4,  4,  4, ..., 34, 34, 34])

In [4]:
for x in dp["y"].batch(num_workers=4):
    break


In [5]:
x

(32,)


ValueError: Wrong number of items passed 32, placement implies 0

In [6]:
for x in dp[["input"]].batch(num_workers=4):
    break

None
None
WorkerInfo(id=3, num_workers=4, seed=752718725976105268, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=1, num_workers=4, seed=752718725976105266, dataset=DataPane(num_rows: 11483))WorkerInfo(id=2, num_workers=4, seed=752718725976105267, dataset=DataPane(num_rows: 11483))

WorkerInfo(id=0, num_workers=4, seed=752718725976105265, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=2, num_workers=4, seed=752718725976105267, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=3, num_workers=4, seed=752718725976105268, dataset=DataPane(num_rows: 11483))
WorkerInfo(id=0, num_workers=4, seed=752718725976105265, dataset=DataPane(num_rows: 11483))WorkerInfo(id=1, num_workers=4, seed=752718725976105266, dataset=DataPane(num_rows: 11483))



In [10]:
x["input"][0]

TypeError: 'NoneType' object is not subscriptable

In [13]:
x["input"].shape

(32, 3, 224, 224)

In [14]:
x["input"][0]

TypeError: 'NoneType' object is not subscriptable

In [29]:
import numpy as np
from multiprocessing.queues import Queue, _ForkingPickler
from robustnessgym.mosaic import NumpyArrayColumn
x = NumpyArrayColumn(np.ones(10))
obj = _ForkingPickler.dumps(x)

__new__
__aray_finalize__


TypeError: a bytes-like object is required, not '_io.BytesIO'

In [42]:
import io
import pickle
x = NumpyArrayColumn(np.ones(10))
#x = np.ones(10)

buf = io.BytesIO()
pickler = pickle.Pickler(buf, protocol=None)
pickler.dump(x)
pickle.loads(buf.getbuffer())

__new__
__aray_finalize__
__aray_finalize__
obj is None


ValueError: 

In [44]:
import io
import pickle
x = NumpyArrayColumn(np.ones(10))
#x = np.ones(10)

buf = pickle.dumps(x)
pickle.loads(buf)

__new__
__aray_finalize__
__aray_finalize__
obj is None


ValueError: 

In [13]:
from robustnessgym.mosaic import NumpyArrayColumn
import numpy as np
x = NumpyArrayColumn(np.ones(10))
out = x.__reduce__()

In [18]:
def _reconstruct_numpy_array_column(_reconstruct_fn, *args, **kwargs):
    return NumpyArrayColumn.from_array(_reconstruct_fn(*args, **kwargs))

In [20]:
_reconstruct_numpy_array_column(out[0], out[1][0], out[2][1], out[2][2])

(10,)


NumpyArrayColumn(array([1., 1...., 1., 1., 1.]))

In [26]:
import pickle
buf = pickle.dumps(x)
pickle.loads(buf)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
out = x.__reduce__()
out[0](np.ndarray, out[1][1], out[1][2]).__setstate()

array([], dtype=int8)

In [29]:
out[2]

(1,
 (10,),
 dtype('float64'),
 False,
 b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?')

In [30]:
inspect
inspnp.zeros(10).__setstate__

<function ndarray.__setstate__>

In [19]:
out

(11483,)


ValueError: Wrong number of items passed 11483, placement implies 0

In [20]:
dp["y"]

(11483,)
/home/common/envs/conda/envs/rg-sabri/lib/python3.8/site-packages/IPython/core/formatters.py:368: FormatterWarning: text/html formatter returned invalid type <class 'pandas.core.series.Series'> (expected <class 'str'>) for object: NumpyArrayColumn(array([ 4,  4..., 34, 34, 34]))
  warnings.warn(


NumpyArrayColumn(array([ 4,  4..., 34, 34, 34]))